/* ──────────────────────────────────────────────────────────────
   AI DEFINITIONS LIBRARY — static, searchable glossary
   Plain-English translations of model-release language.
   Edit this file to grow the library; no backend involved.
   ────────────────────────────────────────────────────────────── */

export type Freshness = "stable" | "emerging" | "fast-moving";

export interface Definition {
  id: string;
  term: string;
  shortDefinition: string;
  plainEnglish: string;
  whyItMatters: string;
  example: string;
  category: string;
  aliases?: string[];
  relatedTerms?: string[];
  freshness?: Freshness;
}

export const DEF_CATEGORIES = [
  "Models",
  "Context & memory",
  "Reasoning",
  "Benchmarks",
  "Agents",
  "Open weights",
  "Pricing",
  "Multimodal",
  "Infrastructure",
  "Safety",
] as const;

// Soft accent per category (rails + pills), drawn from the lab palette family
export const DEF_CATEGORY_COLORS: Record<string, string> = {
  "Models": "#6E8AFF",
  "Context & memory": "#5BD0B0",
  "Reasoning": "#B07CFF",
  "Benchmarks": "#F2934A",
  "Agents": "#2DD4A7",
  "Open weights": "#8B7CF5",
  "Pricing": "#E06C9F",
  "Multimodal": "#46C2D6",
  "Infrastructure": "#C7CEDB",
  "Safety": "#EC6A6A",
};

export const DEFINITIONS: Definition[] = [
  {
    id: "context-window", term: "Context window", category: "Context & memory", freshness: "stable",
    aliases: ["context length", "context size"],
    shortDefinition: "How much text a model can consider at once.",
    plainEnglish: "The model's working memory for one conversation or task. Everything you paste in, plus everything it has said back, has to fit inside this limit.",
    whyItMatters: "It decides whether you can hand a model one paragraph, one document, or an entire project at a time.",
    example: "A 200K context window holds roughly a 350-page book; 1M holds a small archive.",
    relatedTerms: ["Token", "1M context", "Long-context retrieval"],
  },
  {
    id: "1m-context", term: "1M context", category: "Context & memory", freshness: "fast-moving",
    aliases: ["million token context"],
    shortDefinition: "A context window of about one million tokens.",
    plainEnglish: "Marketing shorthand for 'you can paste in a very large amount of material at once' — several books' worth of text.",
    whyItMatters: "Big contexts reduce the need for retrieval tricks, but models can still lose accuracy in the middle of huge inputs.",
    example: "Dropping a whole codebase or a year of council minutes into one prompt.",
    relatedTerms: ["Context window", "Long-context retrieval", "RAG"],
  },
  {
    id: "token", term: "Token", category: "Context & memory", freshness: "stable",
    shortDefinition: "The small chunk of text models actually read and write.",
    plainEnglish: "Models don't see words — they see tokens, pieces of words about 3–4 characters long in English. 'Release' might be one token; 'Radar' another.",
    whyItMatters: "Everything is measured in tokens: context limits, speed, and especially price.",
    example: "1,000 tokens ≈ 750 English words, or about a page and a half.",
    relatedTerms: ["Input token", "Output token", "Context window"],
  },
  {
    id: "input-token", term: "Input token", category: "Pricing", freshness: "stable",
    aliases: ["prompt token"],
    shortDefinition: "Tokens you send to the model — your prompt and attachments.",
    plainEnglish: "Everything the model reads counts as input: your question, the document you pasted, the conversation so far.",
    whyItMatters: "Input is billed separately from output and is usually 4–5× cheaper. Long documents cost on the way in.",
    example: "'$5/M input' means a 100K-token report costs about $0.50 to show the model once.",
    relatedTerms: ["Output token", "Prompt caching"],
  },
  {
    id: "output-token", term: "Output token", category: "Pricing", freshness: "stable",
    aliases: ["completion token"],
    shortDefinition: "Tokens the model writes back to you.",
    plainEnglish: "The model's answer, billed per token — and almost always the expensive direction.",
    whyItMatters: "Verbose models cost more per task even at the same listed price. Reasoning models can burn thousands of hidden 'thinking' tokens that bill as output.",
    example: "At $25/M output, a 2,000-token answer costs about 5 cents.",
    relatedTerms: ["Input token", "Reasoning model"],
  },
  {
    id: "multimodal", term: "Multimodal", category: "Multimodal", freshness: "stable",
    aliases: ["omnimodal", "vision model"],
    shortDefinition: "Handles more than text — images, audio, sometimes video.",
    plainEnglish: "A multimodal model can look at a screenshot, listen to audio, or watch a clip, not just read text. 'Natively multimodal' means it was trained that way from the start rather than having vision bolted on.",
    whyItMatters: "It's the difference between describing a design to the model and just showing it.",
    example: "Pasting a client's homepage screenshot and asking what to fix.",
    relatedTerms: ["Frontier model"],
  },
  {
    id: "reasoning-model", term: "Reasoning model", category: "Reasoning", freshness: "fast-moving",
    aliases: ["thinking model", "chain of thought"],
    shortDefinition: "A model that 'thinks' through steps before answering.",
    plainEnglish: "Instead of answering instantly, it works through the problem internally — often for seconds or minutes — then gives a more reliable answer. Some let you watch the thinking; most charge for it as output tokens.",
    whyItMatters: "Much better at math, debugging, and multi-step planning; slower and pricier for simple questions.",
    example: "o-series, DeepSeek R1, and Claude's extended thinking are all reasoning modes.",
    relatedTerms: ["Output token", "Agent"],
  },
  {
    id: "frontier-model", term: "Frontier model", category: "Models", freshness: "fast-moving",
    aliases: ["flagship model", "SOTA"],
    shortDefinition: "A lab's most capable current model — the leading edge.",
    plainEnglish: "The best a lab can ship today. 'Frontier' is also used for the industry's overall leading edge, where capability (and risk debate) lives.",
    whyItMatters: "Frontier models set the benchmark everyone else is measured against — and carry frontier prices.",
    example: "Opus, GPT flagships, and Gemini Pro tiers are frontier; their mini/flash siblings are not.",
    relatedTerms: ["Closed model", "Benchmark"],
  },
  {
    id: "open-weight", term: "Open-weight model", category: "Open weights", freshness: "stable",
    aliases: ["open weights", "self-hostable"],
    shortDefinition: "The trained model file is published — you can run it yourself.",
    plainEnglish: "The lab releases the actual 'brain' (the weights) for download. You can host it on your own hardware, fine-tune it, and never send data to the lab.",
    whyItMatters: "Free per-token, private, and customizable — but you supply the hardware and upkeep.",
    example: "Llama, DeepSeek, Qwen, GLM, and Gemma all publish weights.",
    relatedTerms: ["Open-source model", "Quantization", "Fine-tuning"],
  },
  {
    id: "open-source", term: "Open-source model", category: "Open weights", freshness: "stable",
    shortDefinition: "Open weights plus a genuinely permissive license.",
    plainEnglish: "Often used loosely as a synonym for open-weight, but strictly it means the license is truly open (like Apache 2.0) — no usage carve-outs, commercial use allowed, sometimes training data documented.",
    whyItMatters: "License details decide whether you can build client work on a model. 'Open' in a headline isn't a license.",
    example: "Qwen's Apache 2.0 release is open-source; Llama's license has a large-company carve-out.",
    relatedTerms: ["Open-weight model"],
  },
  {
    id: "closed-model", term: "Closed model", category: "Models", freshness: "stable",
    aliases: ["proprietary model", "API-only"],
    shortDefinition: "Only available through the lab's API or app — no weights.",
    plainEnglish: "You rent access per token; the model itself stays on the lab's servers. Most frontier models are closed.",
    whyItMatters: "Best capability with zero infrastructure, but ongoing cost, rate limits, and your data transits their servers.",
    example: "Claude, GPT, and Gemini flagships are all closed.",
    relatedTerms: ["Frontier model", "Rate limit"],
  },
  {
    id: "benchmark", term: "Benchmark", category: "Benchmarks", freshness: "stable",
    shortDefinition: "A standardized test used to score and compare models.",
    plainEnglish: "A fixed set of problems — coding tasks, exam questions, puzzles — that every model can be run against so the scores are comparable.",
    whyItMatters: "Launch posts lead with benchmark wins. Treat vendor-reported numbers as directional; independent reruns often land lower.",
    example: "SWE-bench (real GitHub bug fixing) and GPQA (hard science questions) headline most releases.",
    relatedTerms: ["Eval", "Frontier model"],
  },
  {
    id: "eval", term: "Eval", category: "Benchmarks", freshness: "stable",
    aliases: ["evaluation"],
    shortDefinition: "Any structured test of model behaviour — including your own.",
    plainEnglish: "Broader than a benchmark: an eval can be a public test suite or just your own checklist of 'does it write our client tone correctly' run against each new model.",
    whyItMatters: "Your own evals beat leaderboards — they measure the work you actually do.",
    example: "Keeping five past client briefs as a private eval for every new creative model.",
    relatedTerms: ["Benchmark"],
  },
  {
    id: "hallucination", term: "Hallucination", category: "Safety", freshness: "stable",
    aliases: ["confabulation"],
    shortDefinition: "The model states something false with full confidence.",
    plainEnglish: "Models predict plausible text, and sometimes the most plausible-sounding answer is simply made up — fake citations, invented stats, confident wrong dates.",
    whyItMatters: "The single biggest reason to keep a human (or a checking step) between a model and anything published.",
    example: "A model inventing a council bylaw number that looks completely real.",
    relatedTerms: ["RAG", "Eval"],
  },
  {
    id: "rag", term: "RAG", category: "Context & memory", freshness: "stable",
    aliases: ["retrieval augmented generation", "retrieval"],
    shortDefinition: "Look facts up first, then have the model answer from them.",
    plainEnglish: "Instead of trusting the model's memory, the system searches your documents, pastes the relevant passages into the prompt, and asks the model to answer from those.",
    whyItMatters: "The standard cure for hallucination when the truth lives in your own files.",
    example: "A support bot that quotes from your actual policy docs instead of guessing.",
    relatedTerms: ["Embeddings", "Vector database", "Hallucination"],
  },
  {
    id: "agent", term: "Agent", category: "Agents", freshness: "fast-moving",
    aliases: ["agentic", "autonomous agent"],
    shortDefinition: "A model in a loop: it plans, acts with tools, and keeps going.",
    plainEnglish: "Rather than one question/one answer, an agent works toward a goal — runs commands, reads results, fixes its own mistakes, repeats — until done or stopped.",
    whyItMatters: "'Agentic' is the current frontier battleground; it's what 'the model can work for hours' claims are about.",
    example: "Claude Code refactoring a project across dozens of files in one run.",
    relatedTerms: ["Tool use", "Reasoning model", "MCP"],
  },
  {
    id: "tool-use", term: "Tool use", category: "Agents", freshness: "stable",
    shortDefinition: "The model can call outside tools — search, code, APIs.",
    plainEnglish: "The model isn't limited to writing text: it can decide to run a calculator, hit an API, search the web, or execute code, then use the result in its answer.",
    whyItMatters: "Tools are how models get current facts and real abilities instead of educated guesses.",
    example: "A model checking live exchange rates instead of recalling stale ones.",
    relatedTerms: ["Function calling", "Agent"],
  },
  {
    id: "function-calling", term: "Function calling", category: "Agents", freshness: "stable",
    aliases: ["structured outputs"],
    shortDefinition: "The developer mechanism behind tool use.",
    plainEnglish: "You describe your functions to the model ('book_meeting takes a date and a name'), and it replies with a structured request to call one — which your code then executes.",
    whyItMatters: "It's how chat models get wired into real products and workflows reliably.",
    example: "A booking bot emitting {function: 'book_meeting', date: '2026-06-15'} instead of prose.",
    relatedTerms: ["Tool use", "Agent"],
  },
  {
    id: "mcp", term: "MCP", category: "Agents", freshness: "fast-moving",
    aliases: ["Model Context Protocol"],
    shortDefinition: "An open standard for plugging tools and data into models.",
    plainEnglish: "Instead of every app inventing its own integrations, MCP is a shared plug format: build one MCP server for your data and any compatible model client can use it.",
    whyItMatters: "Rapidly becoming the USB of AI tooling — it's how assistants reach your calendar, files, and services.",
    example: "One MCP server for your project database, usable from Claude, IDEs, and other clients alike.",
    relatedTerms: ["Tool use", "Agent"],
  },
  {
    id: "fine-tuning", term: "Fine-tuning", category: "Models", freshness: "stable",
    shortDefinition: "Extra training to specialize an existing model.",
    plainEnglish: "Take a trained model and continue training it on your examples so it picks up your style, format, or domain — cheaper than training from scratch by orders of magnitude.",
    whyItMatters: "The route to a model that writes like your studio, though good prompting covers most cases first.",
    example: "Fine-tuning a small model on 500 of your past briefs-to-copy pairs.",
    relatedTerms: ["Open-weight model", "Distillation", "Post-training"],
  },
  {
    id: "distillation", term: "Distillation", category: "Models", freshness: "stable",
    shortDefinition: "Teaching a small model to imitate a big one.",
    plainEnglish: "Run a large 'teacher' model, collect its answers, train a small 'student' on them. The student gets surprisingly close at a fraction of the size and cost.",
    whyItMatters: "Why tiny models keep beating last year's giants — and why phone-sized models are now useful.",
    example: "Phi models are famous distillation results.",
    relatedTerms: ["Fine-tuning", "Quantization"],
  },
  {
    id: "quantization", term: "Quantization", category: "Infrastructure", freshness: "stable",
    aliases: ["4-bit", "8-bit", "GGUF"],
    shortDefinition: "Compressing a model's numbers so it runs on smaller hardware.",
    plainEnglish: "Store the model's weights with less precision (like rounding prices to the nearest dollar). The file shrinks 2–4×, runs on cheaper GPUs, and loses only a little quality.",
    whyItMatters: "It's what makes 'runs on a laptop' possible for serious open models.",
    example: "A 70B model squeezed from 140GB to ~40GB to fit one GPU.",
    relatedTerms: ["Open-weight model", "Inference"],
  },
  {
    id: "moe", term: "Mixture of experts", category: "Models", freshness: "stable",
    aliases: ["MoE", "sparse model", "active parameters"],
    shortDefinition: "A huge model where only a slice activates per token.",
    plainEnglish: "The model is built from many specialist sub-networks ('experts'); a router picks a few per token. So a '1T parameter' MoE might only use 30B at a time — big-model quality, smaller-model running cost.",
    whyItMatters: "Decodes spec sheets: '230B total / 10B active' means cheap to serve, not 23× weaker.",
    example: "DeepSeek, Kimi, Llama 4, and MiniMax are all MoE designs.",
    relatedTerms: ["Inference", "Open-weight model"],
  },
  {
    id: "latency", term: "Latency", category: "Infrastructure", freshness: "stable",
    aliases: ["time to first token", "TTFT"],
    shortDefinition: "How long you wait for the model to respond.",
    plainEnglish: "Two parts: the pause before the first word appears, then the streaming speed after. 'Fast' models win on both.",
    whyItMatters: "For anything interactive — chatbots, autocomplete, voice — latency matters more than a few benchmark points.",
    example: "Haiku/Flash-class models exist mostly to win the latency game.",
    relatedTerms: ["Inference", "Rate limit"],
  },
  {
    id: "inference", term: "Inference", category: "Infrastructure", freshness: "stable",
    aliases: ["serving"],
    shortDefinition: "Running a trained model to get answers.",
    plainEnglish: "Training builds the model; inference is using it. Every prompt you send is inference, and inference cost is what API pricing reflects.",
    whyItMatters: "When labs say a model is 'cheap to serve', they mean inference — that's what shows up on your bill.",
    example: "'Inference provider' = a company that hosts open models and sells per-token access.",
    relatedTerms: ["Training", "Latency", "Quantization"],
  },
  {
    id: "training", term: "Training", category: "Models", freshness: "stable",
    shortDefinition: "Building a model by showing it enormous amounts of data.",
    plainEnglish: "Months of GPU time adjusting billions of numbers until the model predicts text well. Done once by the lab; you never train, you use the result.",
    whyItMatters: "Training cost ('trained for $5.6M') signals how efficient a lab is — and how fast they can iterate.",
    example: "Grok 3 trained on a 200,000-GPU cluster.",
    relatedTerms: ["Pretraining", "Post-training", "Inference"],
  },
  {
    id: "pretraining", term: "Pretraining", category: "Models", freshness: "stable",
    shortDefinition: "The first, biggest phase: learning language from raw text.",
    plainEnglish: "The model reads a giant slice of the internet and learns to predict the next token. After pretraining it's knowledgeable but raw — not yet helpful or safe.",
    whyItMatters: "Pretraining scale sets a model's ceiling; 'first fully retrained base since X' means a new foundation, not a tune-up.",
    example: "GPT-5.5 shipping on a freshly pretrained base was the headline, not the version number.",
    relatedTerms: ["Post-training", "Training"],
  },
  {
    id: "post-training", term: "Post-training", category: "Models", freshness: "emerging",
    shortDefinition: "Everything after pretraining that shapes behaviour.",
    plainEnglish: "Instruction-following, tone, refusals, tool skills, reasoning habits — taught after the base model exists, via fine-tuning and feedback methods like RLHF.",
    whyItMatters: "Most point releases (4.5 → 4.6) are post-training improvements: same brain, much better behaviour.",
    example: "Llama 3.3 70B matching a 405B model 'via post-training advances'.",
    relatedTerms: ["RLHF", "Fine-tuning", "Pretraining"],
  },
  {
    id: "rlhf", term: "RLHF", category: "Models", freshness: "stable",
    aliases: ["reinforcement learning from human feedback"],
    shortDefinition: "Training models on human preferences between answers.",
    plainEnglish: "Humans (or trained reward models) rate which of two answers is better; the model is nudged toward the preferred kind. It's why assistants are polite and on-task.",
    whyItMatters: "The reason raw internet-trained models feel like helpful assistants instead of autocomplete.",
    example: "A model learning that 'concise with a code sample' beats 'ten paragraphs of theory'.",
    relatedTerms: ["Post-training"],
  },
  {
    id: "synthetic-data", term: "Synthetic data", category: "Models", freshness: "emerging",
    shortDefinition: "Training data generated by models instead of humans.",
    plainEnglish: "Labs increasingly have strong models write problems, solutions, and dialogues to train the next model on — quality-filtered automatically.",
    whyItMatters: "It's how labs keep scaling after running low on good human text, and a quiet driver of reasoning gains.",
    example: "Millions of model-generated, machine-verified math solutions feeding the next reasoning model.",
    relatedTerms: ["Distillation", "Pretraining"],
  },
  {
    id: "embeddings", term: "Embeddings", category: "Context & memory", freshness: "stable",
    aliases: ["vectors", "embedding model"],
    shortDefinition: "Text turned into numbers that capture meaning.",
    plainEnglish: "An embedding model converts text into a list of numbers where similar meanings land close together — so 'invoice overdue' and 'unpaid bill' end up neighbours.",
    whyItMatters: "The backbone of semantic search and RAG: it's how systems find relevant passages, not just keyword matches.",
    example: "Searching 'angry customer emails' and matching messages that never use the word 'angry'.",
    relatedTerms: ["Vector database", "RAG"],
  },
  {
    id: "vector-database", term: "Vector database", category: "Context & memory", freshness: "stable",
    aliases: ["vector store"],
    shortDefinition: "A database built to search embeddings fast.",
    plainEnglish: "Stores millions of embeddings and answers 'what's most similar to this?' in milliseconds. The retrieval half of RAG.",
    whyItMatters: "If you want a model to answer from your documents, they usually live here first.",
    example: "Pinecone, pgvector, or SQLite extensions doing similarity search over your docs.",
    relatedTerms: ["Embeddings", "RAG"],
  },
  {
    id: "long-context-retrieval", term: "Long-context retrieval", category: "Context & memory", freshness: "emerging",
    aliases: ["needle in a haystack"],
    shortDefinition: "How well a model finds facts buried deep in a huge prompt.",
    plainEnglish: "A giant context window is only useful if the model can actually find page 412. 'Needle in a haystack' tests hide a fact in a long document and check recall.",
    whyItMatters: "Two models with '1M context' can differ wildly in whether the middle of that million is actually usable.",
    example: "Perfect recall at 100K but missed details at 800K — same advertised window.",
    relatedTerms: ["Context window", "1M context", "RAG"],
  },
  {
    id: "rate-limit", term: "Rate limit", category: "Infrastructure", freshness: "stable",
    aliases: ["RPM", "TPM", "quota"],
    shortDefinition: "Caps on how fast/much you can call an API.",
    plainEnglish: "Providers cap requests per minute and tokens per minute per account tier. Hit the cap and calls fail with a 429 until the window resets.",
    whyItMatters: "The thing that breaks your automation at the worst moment; bulk jobs need retry logic and pacing.",
    example: "A batch of 500 article drafts throttled to a crawl on a starter tier.",
    relatedTerms: ["Latency", "Closed model"],
  },
  {
    id: "context-caching", term: "Context caching", category: "Pricing", freshness: "emerging",
    aliases: ["cache hit"],
    shortDefinition: "Reusing an already-processed prompt at a steep discount.",
    plainEnglish: "If you send the same big preamble repeatedly (a system prompt, a reference doc), providers can cache its processed form and charge a fraction for re-reading it.",
    whyItMatters: "Can cut input costs ~90% for agents and chatbots that re-send the same context every turn.",
    example: "A 50K-token style guide cached once, then nearly free on every subsequent call.",
    relatedTerms: ["Prompt caching", "Input token"],
  },
  {
    id: "prompt-caching", term: "Prompt caching", category: "Pricing", freshness: "emerging",
    shortDefinition: "The same idea as context caching — cached prompt prefixes billed cheap.",
    plainEnglish: "Different providers use 'prompt caching' or 'context caching' for the same mechanism: identical prompt beginnings are recognized and billed at a cached rate.",
    whyItMatters: "Structure prompts with the stable part first and the changing part last, and the savings happen automatically.",
    example: "System prompt + tools first, user question last — cache hits on every call.",
    relatedTerms: ["Context caching", "Input token"],
  },
];
